#!/usr/bin/perl

use 5.022;
use warnings;

use Strong::Random;
use Getopt::Long qw(GetOptions);


my $usage = "Usage:\n\t$0 [--help|-h] [--pwdgen] [--input|-i=inputfile] [-d crypted_file] [--output|-o=outputfile] [--salt|-s=random_string_for_crypter] [input] [-]";
my %args = process_command_line(qw/i|input=s pwdgen d=s o|output=s s|salt=s h|help/, $usage);
my $stdin = ($ARGV[-1] // '') eq '-';

if ($args{pwdgen}) {
	my $rand = new Strong::Random;
	my $pwd = join'', map +(0..9,'a'..'z','A'..'Z')[$rand->rand(10+26*2)], 1..64;
	say $pwd;
	exit;
}

my $uncrypt = $args{d};
my $salt = $args{salt};
say $usage and exit if !$salt && !$uncrypt;
my $file = $args{input} // $ARGV[-1] // '';
my $output = $args{output};
say $usage and exit  if !$output && !$uncrypt;

if ($uncrypt) {
	$file = $uncrypt;
	
	$stdin = 1 if !$output;
	
	die "Not input file $file" unless -f $file;
	die "No keyfile " . $file . '.key' unless -f $file . '.key';

	my $input = '';

	my $fh;
	open $fh, $file . '.key';
	my $key = join '', <$fh>;
	close $fh;

	my @random = map {{
		generator 	=> new Strong::Random($_), 
		seed 		=> $_ 
	}} split /,/, $key;



	my $fo;
	if (!$stdin) {
		open $fo, '>', $output;
	} else {
		$fo = \*STDOUT;
	}
	binmode $fo;

	open $fh, $file;
	binmode $fh;

	my $n = 0;
	while (my $str = <$fh>) {
		my @input = split //, $str;
		my $out = '';
		for (my $i = 0 ; $i < scalar @input ; $i ++) {
			my $chr = $input[$i];
			my $ord = ord $chr;
			
			
			my $r = $random[$n];
			$n = 0 if (++$n >= scalar @random);
			my $s = $r->{generator}->rand(256);

			
			my $ord2 = $ord ^ $s;
			
			$out .= chr $ord2;
		}
		print $fo $out;
	}
	close $fh;

	if (!$stdin) {
		close $fo;
	}

} else {
	die "Not input file $file" if !$stdin && !-f $file;

	# Init randomerz
	my @random;
	my $strong = $args{strong} || 256;
	for (1..int(length($salt)/2+.5)) {
		my $rnd = new Strong::Random;
		$rnd->rand();
		
		my $p = substr($salt, 2*$_-2, 2);
		$p .= ' ' if (length $p == 1);
		
		my $x = join '', map {ord} split //, $p;
		
		for (1..$x) {$rnd->rand()}
		
		my $seed = sprintf("%.8f", $rnd->{seed});
		push @random, {
			generator 	=> new Strong::Random($seed),
			seed		=> $seed,
		};
	}

	my $input = '';

	my $n = 0;

	my $fo;
	open $fo, '>', $output;
	binmode $fo;

	my $fi;
	if (!$stdin) {
		open $fi, $file;
		binmode $fi;
	} else {
		binmode STDIN;
		$fi = \*STDIN;
	}

	while (my $str = <$fi>) {
		my @input = split //, $str;

		my $out = '';
		for (my $i = 0 ; $i < scalar @input ; $i ++) {
			my $chr = $input[$i];
			my $ord = ord $chr;
			
			
			my $r = $random[$n];
			$n = 0 if (++$n >= scalar @random);
			my $s = $r->{generator}->rand(256);
			
			my $ord2 = $ord ^ $s;
			
			$out .= chr $ord2;
		}
		
		print $fo $out;
	}

	if (!$stdin) {
		close $fi;
	}

	close $fo;

	my $fh;
	open $fh, '>', $output .'.key';
	say $fh join ',', map {$_->{seed}} @random;
	close $fh;
}



# Usefull util for parsing command-line
sub process_command_line {
	my $usage = pop; # Get last param, it's Usage text
	my @opts  = @_;  # Get params
	
	# Prepare from GetOptions syntax option to key-names
	my $prepare = sub {
		my $opt = shift;
		$opt =~ s/\=s$//;
		$opt =~ s/^\w\|(\w+)$/$1/;
		return $opt;
	};
	
	my %args = ();
	GetOptions(map {$_ => \$args{$prepare->($_)}} @opts);
	
	# Show usage, it catchet --help command-line param
	say $usage and exit() if $args{help};
	
	return %args;
}


