#!/usr/bin/perl

use 5.022;
use warnings;

use Strong::Random;
use Getopt::Long qw(GetOptions);


my $usage = "Usage:\n\t$0 [--help|-h] [--input|-i=inputfile] [--output|-o=outputfile]";
my %args = process_command_line(qw/i|input=s o|output=s p|password=s h|help/, $usage);

my $file = $args{input} or say $usage and exit;
my $output = $args{output} or say $usage and exit;

my $input = '';

my $fh;
open $fh, $file;
binmode $fh;
$input = join '', <$fh>;
close $fh;

open $fh, $file . '.key';
my $key = join '', <$fh>;
close $fh;

my @random = map {{
	generator 	=> new Strong::Random($_), 
	seed 		=> $_ 
}} split /,/, $key;

my @input = split //, $input;

my $n = 0;



my $out = '';
for (my $i = 0 ; $i < scalar @input ; $i ++) {
	my $chr = $input[$i];
	my $ord = ord $chr;
	
	
	my $r = $random[$n];
	$n = 0 if (++$n >= scalar @random);
	my $s = $r->{generator}->rand(256);

	
	my $ord2 = $ord ^ $s;
	
	$out .= chr $ord2;
}

if ($output) {
	my $fh;
	open $fh, '>', $output;
	print $fh $out;
	close $fh;
}





# Usefull util for parsing command-line
sub process_command_line {
	my $usage = pop; # Get last param, it's Usage text
	my @opts  = @_;  # Get params
	
	# Prepare from GetOptions syntax option to key-names
	my $prepare = sub {
		my $opt = shift;
		$opt =~ s/\=s$//;
		$opt =~ s/^\w\|(\w+)$/$1/;
		return $opt;
	};
	
	my %args = ();
	GetOptions(map {$_ => \$args{$prepare->($_)}} @opts);
	
	# Show usage, it catchet --help command-line param
	say $usage and exit() if $args{help};
	
	return %args;
}

1;
